import { MenuCategory } from "./types";

/**
 * Source of truth: the LOVBITES menu workbook as provided in the brief.
 * Names, prices and items are transcribed as-is — nothing invented, nothing removed.
 * ⭐ = hero/signature, ❤️ = date/couple pick, as explicitly marked in the source.
 */
export const MENU: MenuCategory[] = [
  {
    id: "healthy-breakfast",
    number: "01",
    title: "Healthy Breakfast",
    navGroup: "breakfast",
    emotionalLine: "Start your day the right way.",
    mood: "bright",
    timeContext: "morning",
    items: [
      { id: "millet-idli", name: "Millet Idli", price: 139, diet: "veg" },
      { id: "mini-classic-idli", name: "Mini Classic Idli", price: 99, diet: "veg" },
      { id: "chana-power-chaat", name: "Chana Power Chaat", price: 129, diet: "veg" },
      { id: "protein-poha", name: "Protein Poha with Paneer & Soya", price: 149, diet: "veg", protein: true },
      { id: "paneer-stuffed-chilla", name: "Paneer Stuffed Chilla", price: 189, diet: "veg" },
      { id: "sprout-power-bowl", name: "Fresh Sprout Power Bowl", price: 169, diet: "veg" },
      { id: "chickpea-feta-salad", name: "Chickpea & Feta Salad", price: 199, diet: "veg" },
      { id: "paneer-power-salad", name: "Paneer Power Salad", price: 219, diet: "veg", protein: true },
    ],
  },
  {
    id: "indian-breakfast",
    number: "02",
    title: "Indian Breakfast",
    navGroup: "breakfast",
    emotionalLine: "Comfort food, made modern.",
    mood: "bright",
    timeContext: "morning",
    items: [
      { id: "chole-bhature", name: "Classic Chole Bhature", price: 159, diet: "veg" },
      { id: "pav-bhaji", name: "Mumbai Pav Bhaji", price: 149, diet: "veg" },
      { id: "aloo-power-paratha", name: "Desi Aloo Power Paratha", price: 149, diet: "veg" },
      { id: "paneer-power-paratha", name: "Paneer Power Paratha", price: 179, diet: "veg" },
    ],
  },
  {
    id: "protein-breakfast",
    number: "03",
    title: "Protein Breakfast",
    navGroup: "protein",
    emotionalLine: "Fuel up before you take on the day.",
    mood: "clean",
    timeContext: "morning",
    items: [
      { id: "paneer-tikka-protein-wrap", name: "Paneer Tikka Protein Wrap", price: 199, diet: "veg", protein: true },
      { id: "grilled-chicken-protein-wrap", name: "Grilled Chicken Protein Wrap", price: 229, diet: "nonveg", protein: true },
      { id: "egg-chicken-power-wrap", name: "Egg Chicken Power Wrap", price: 249, diet: "nonveg", protein: true },
    ],
  },
  {
    id: "egg-corner",
    number: "04",
    title: "Egg Corner",
    navGroup: "breakfast",
    emotionalLine: "Simple. Classic. Done right.",
    mood: "bright",
    timeContext: "morning",
    items: [
      { id: "egg-masala-omelette", name: "2 Egg Masala Omelette", price: 99, diet: "egg" },
      { id: "egg-white-omelette", name: "4 Egg White Omelette", price: 109, diet: "egg", protein: true },
      { id: "egg-bhurji", name: "Masala Egg Bhurji", price: 129, diet: "egg" },
    ],
  },
  {
    id: "sandwich-burger",
    number: "05",
    title: "Sandwich & Burger",
    navGroup: "burgers",
    emotionalLine: "Stacked, grilled, unmistakably LOVBITES.",
    mood: "bold",
    timeContext: "all-day",
    items: [
      { id: "veg-cheese-grilled-sandwich", name: "Veg Cheese Grilled Sandwich", price: 250, diet: "veg" },
      { id: "paneer-tikka-sandwich", name: "Paneer Tikka Sandwich", price: 279, diet: "veg" },
      { id: "grilled-chicken-sandwich", name: "Grilled Chicken Sandwich", price: 249, diet: "nonveg" },
      { id: "classic-veg-burger", name: "Classic Veg Burger", price: 169, diet: "veg" },
      { id: "paneer-tikka-burger", name: "Paneer Tikka Burger", price: 199, diet: "veg" },
      { id: "crispy-chicken-burger", name: "Crispy Chicken Burger", price: 269, diet: "nonveg" },
    ],
  },
  {
    id: "pizza",
    number: "06",
    title: "Pizza",
    navGroup: "pizza",
    emotionalLine: "Stretched cheese. Stone-fired soul.",
    mood: "bold",
    timeContext: "all-day",
    items: [
      { id: "margherita-pizza", name: "Margherita Pizza", price: 229, diet: "veg" },
      { id: "farm-fresh-pizza", name: "Farm Fresh Pizza", price: 279, diet: "veg" },
      { id: "peri-peri-paneer-pizza", name: "Peri Peri Paneer Pizza", price: 329, diet: "veg" },
      { id: "bbq-chicken-pizza", name: "BBQ Chicken Pizza", price: 349, diet: "nonveg" },
      { id: "peri-peri-chicken-pizza", name: "Peri Peri Chicken Pizza", price: 349, diet: "nonveg" },
    ],
  },
  {
    id: "pasta",
    number: "07",
    title: "Pasta",
    navGroup: "pasta",
    emotionalLine: "Slow sauce, fast craving.",
    mood: "bold",
    timeContext: "all-day",
    items: [
      { id: "veg-arrabbiata-pasta", name: "Veg Arrabbiata Pasta", price: 229, diet: "veg" },
      { id: "veg-alfredo-pasta", name: "Veg Alfredo Pasta", price: 249, diet: "veg" },
      { id: "chicken-arrabbiata-pasta", name: "Chicken Arrabbiata Pasta", price: 279, diet: "nonveg" },
      { id: "chicken-alfredo-pasta", name: "Chicken Alfredo Pasta", price: 299, diet: "nonveg" },
    ],
  },
  {
    id: "quick-bites",
    number: "08",
    title: "Quick Bites",
    navGroup: "quick-bites",
    emotionalLine: "Small plates. Big cravings.",
    mood: "bold",
    timeContext: "all-day",
    items: [
      { id: "classic-fries", name: "Classic Fries", price: 129, diet: "veg" },
      { id: "peri-peri-fries", name: "Peri Peri Fries", price: 149, diet: "veg" },
      { id: "cheese-loaded-fries", name: "Cheese Loaded Fries", price: 199, diet: "veg" },
      { id: "cheese-loaded-nachos", name: "Cheese Loaded Nachos", price: 219, diet: "veg" },
      { id: "veg-momos", name: "Veg Momos", price: 149, diet: "veg" },
      { id: "chicken-momos", name: "Chicken Momos", price: 189, diet: "nonveg" },
    ],
  },
  {
    id: "fried-chicken",
    number: "09",
    title: "Fried Chicken",
    navGroup: "chicken",
    emotionalLine: "Crispy. Loud. Unapologetic.",
    mood: "bold",
    timeContext: "all-day",
    items: [
      { id: "lovbites-chicken-bucket", name: "LovBites Chicken Bucket", price: 499, diet: "nonveg" },
      { id: "chicken-popcorn", name: "Chicken Popcorn", price: 229, diet: "nonveg" },
      { id: "peri-peri-wings", name: "Peri Peri Wings", price: 279, diet: "nonveg" },
      { id: "korean-crispy-chicken", name: "Korean Crispy Chicken", price: 299, diet: "nonveg", hero: true },
    ],
  },
  {
    id: "protein-power-bowls",
    number: "10",
    title: "Protein Power Bowls",
    navGroup: "protein",
    emotionalLine: "Good food. Stronger choices.",
    mood: "clean",
    timeContext: "all-day",
    items: [
      { id: "paneer-power-bowl", name: "Paneer Power Bowl", price: 249, diet: "veg", protein: true, hero: true },
      { id: "rajma-protein-bowl", name: "Rajma Protein Bowl", price: 249, diet: "veg", protein: true },
      { id: "grilled-chicken-power-bowl", name: "Grilled Chicken Power Bowl", price: 299, diet: "nonveg", protein: true, hero: true },
    ],
  },
  {
    id: "coffee",
    number: "11",
    title: "Coffee",
    navGroup: "coffee",
    emotionalLine: "Need a little boost?",
    mood: "warm-dark",
    timeContext: "all-day",
    items: [
      { id: "espresso", name: "Espresso", price: 89, diet: "veg" },
      { id: "americano", name: "Hot/Iced Americano", price: 109, diet: "veg" },
      { id: "cappuccino", name: "Cappuccino", price: 139, diet: "veg" },
      { id: "cafe-latte", name: "Cafe Latte", price: 149, diet: "veg" },
      { id: "hazelnut-latte", name: "Hazelnut Latte", price: 169, diet: "veg" },
      { id: "cafe-mocha", name: "Cafe Mocha", price: 169, diet: "veg" },
      { id: "signature-cold-coffee", name: "Signature Cold Coffee", price: 179, diet: "veg", hero: true },
    ],
  },
  {
    id: "protein-shakes",
    number: "12",
    title: "Protein Shakes",
    navGroup: "protein",
    emotionalLine: "Recovery, in a glass.",
    mood: "clean",
    timeContext: "all-day",
    items: [
      { id: "chocolate-whey-shake", name: "Chocolate Whey Shake", price: 249, diet: "veg", protein: true },
      { id: "cold-coffee-whey-shake", name: "Cold Coffee Whey Shake", price: 269, diet: "veg", protein: true, hero: true },
      { id: "peanut-butter-banana-shake", name: "Peanut Butter Banana Protein Shake", price: 279, diet: "veg", protein: true },
    ],
  },
  {
    id: "smoothies",
    number: "13",
    title: "Smoothies",
    navGroup: "protein",
    emotionalLine: "Fresh, blended, honest.",
    mood: "clean",
    timeContext: "all-day",
    items: [
      { id: "berry-smoothie", name: "Berry Smoothie", price: 229, diet: "veg" },
      { id: "green-detox-smoothie", name: "Green Detox Smoothie", price: 219, diet: "veg" },
    ],
  },
  {
    id: "healthy-drinks",
    number: "14",
    title: "Healthy Drinks",
    navGroup: "protein",
    emotionalLine: "Light, cold, refreshing.",
    mood: "clean",
    timeContext: "all-day",
    items: [
      { id: "chia-lemon-refresher", name: "Chia Lemon Refresher", price: 149, diet: "veg" },
      { id: "cucumber-mint-cooler", name: "Cucumber Mint Fresh Cooler", price: 139, diet: "veg" },
      { id: "lemon-mint-cooler", name: "Lemon Mint Fresh Cooler", price: 129, diet: "veg" },
    ],
  },
  {
    id: "shakes",
    number: "15",
    title: "Shakes",
    navGroup: "dessert",
    emotionalLine: "Thick. Indulgent. Unfair.",
    mood: "playful",
    timeContext: "all-day",
    items: [
      { id: "oreo-thick-shake", name: "Oreo Thick Shake", price: 199, diet: "veg" },
      { id: "kitkat-thick-shake", name: "KitKat Thick Shake", price: 199, diet: "veg" },
      { id: "biscoff-thick-shake", name: "Biscoff Thick Shake", price: 229, diet: "veg" },
    ],
  },
  {
    id: "mocktails",
    number: "16",
    title: "Mocktails",
    navGroup: "mocktails",
    emotionalLine: "Something to sip, slowly.",
    mood: "romantic",
    timeContext: "all-day",
    items: [
      { id: "mint-mojito", name: "Mint Mojito", price: 149, diet: "veg" },
      { id: "green-apple-mojito", name: "Green Apple Mojito", price: 169, diet: "veg" },
      { id: "blue-lagoon", name: "Blue Lagoon", price: 169, diet: "veg" },
      { id: "red-romance", name: "LovBites Red Romance", price: 179, diet: "veg", datePick: true },
    ],
  },
  {
    id: "dessert",
    number: "17",
    title: "Dessert",
    navGroup: "dessert",
    emotionalLine: "Save room for this.",
    mood: "playful",
    timeContext: "all-day",
    items: [
      { id: "brownie-ice-cream", name: "Brownie with Ice Cream", price: 169, diet: "veg" },
      { id: "sizzling-brownie-fantasy", name: "Sizzling Brownie Fantasy", price: 229, diet: "veg" },
      { id: "classic-cheesecake-slice", name: "Classic Cheesecake Slice", price: 199, diet: "veg" },
      { id: "date-night-dessert", name: "LovBites Date Night Dessert", price: 299, diet: "veg", datePick: true },
    ],
  },
  {
    id: "combos",
    number: "18",
    title: "Combos",
    navGroup: "combos",
    emotionalLine: "More to love, together.",
    mood: "bold",
    timeContext: "all-day",
    items: [
      { id: "date-combo", name: "LovBites Date Combo", price: 849, diet: "veg", datePick: true },
      { id: "fit-combo", name: "LovBites Fit Combo", price: 399, diet: "veg", protein: true },
    ],
  },
  {
    id: "add-ons",
    number: "19",
    title: "Add-Ons",
    navGroup: "protein",
    emotionalLine: "Make it more you.",
    mood: "clean",
    timeContext: "all-day",
    items: [
      { id: "extra-egg-boost", name: "Extra Egg Boost", price: 35, diet: "egg" },
      { id: "extra-whey-scoop", name: "Extra Whey Scoop", price: 129, diet: "veg", protein: true },
    ],
  },

  // ————— FINE DINE — NOW THE NIGHT BEGINS —————

  {
    id: "soups",
    number: "20",
    title: "Soups",
    navGroup: "fine-dine",
    emotionalLine: "The night begins, warm.",
    mood: "elegant",
    timeContext: "evening",
    items: [
      { id: "veg-manchow-soup", name: "Veg Manchow Soup", price: 149, diet: "veg" },
      { id: "veg-hot-sour-soup", name: "Veg Hot & Sour Soup", price: 149, diet: "veg" },
      { id: "veg-sweet-corn-soup", name: "Veg Sweet Corn Soup", price: 149, diet: "veg" },
      { id: "chicken-hot-sour-soup", name: "Chicken Hot & Sour Soup", price: 169, diet: "nonveg" },
      { id: "chicken-manchow-soup", name: "Chicken Manchow Soup", price: 179, diet: "nonveg" },
    ],
  },
  {
    id: "veg-starters",
    number: "21",
    title: "Veg Starters",
    navGroup: "fine-dine",
    emotionalLine: "Bold flavour, no meat required.",
    mood: "elegant",
    timeContext: "evening",
    items: [
      { id: "crispy-corn", name: "Crispy Corn", price: 179, diet: "veg" },
      { id: "crispy-chilli-baby-corn", name: "Crispy Chilli Baby Corn", price: 199, diet: "veg" },
      { id: "chilli-paneer", name: "Chilli Paneer", price: 229, diet: "veg" },
      { id: "veg-manchurian", name: "Veg Manchurian", price: 199, diet: "veg" },
      { id: "paneer-tikka-starter", name: "Paneer Tikka", price: 269, diet: "veg", hero: true },
      { id: "malai-paneer-tikka", name: "Malai Paneer Tikka", price: 289, diet: "veg" },
    ],
  },
  {
    id: "non-veg-starters",
    number: "22",
    title: "Non-Veg Starters",
    navGroup: "fine-dine",
    emotionalLine: "Sizzle before the main event.",
    mood: "elegant",
    timeContext: "evening",
    items: [
      { id: "chilli-chicken-dry", name: "Chilli Chicken Dry", price: 269, diet: "nonveg" },
      { id: "dragon-chicken", name: "Dragon Chicken", price: 289, diet: "nonveg" },
      { id: "chicken-lollipop", name: "Chicken Lollipop", price: 299, diet: "nonveg" },
      { id: "fish-fingers", name: "Fish Fingers", price: 329, diet: "nonveg" },
    ],
  },
  {
    id: "kebab-tandoor",
    number: "23",
    title: "Kebab & Tandoor",
    navGroup: "fine-dine",
    emotionalLine: "Smoke. Char. Signature spice.",
    mood: "elegant",
    timeContext: "evening",
    items: [
      { id: "chicken-tikka-finedine", name: "Chicken Tikka", price: 329, diet: "nonveg", hero: true },
      { id: "chicken-malai-tikka", name: "Chicken Malai Tikka", price: 349, diet: "nonveg" },
      { id: "chicken-leg-kebab", name: "Chicken Leg Kebab", price: 289, diet: "nonveg" },
      { id: "tandoori-chicken-half", name: "Tandoori Chicken Half", price: 399, diet: "nonveg" },
      { id: "tandoori-chicken-full", name: "Tandoori Chicken Full", price: 699, diet: "nonveg" },
      { id: "tandoori-fish-tikka", name: "Tandoori Fish Tikka", price: 349, diet: "nonveg" },
    ],
  },
  {
    id: "sizzlers",
    number: "24",
    title: "Sizzlers",
    navGroup: "fine-dine",
    emotionalLine: "Steam. Sizzle. Heat.",
    mood: "elegant",
    timeContext: "evening",
    items: [
      { id: "garden-veg-sizzler", name: "Garden Veg Sizzler", price: 429, diet: "veg" },
      { id: "smoky-chicken-sizzler", name: "Smoky Chicken Sizzler", price: 499, diet: "nonveg" },
    ],
  },
  {
    id: "veg-main-course",
    number: "25",
    title: "Veg Main Course",
    navGroup: "fine-dine",
    emotionalLine: "Slow-cooked, deeply comforting.",
    mood: "elegant",
    timeContext: "evening",
    items: [
      { id: "yellow-dal-tadka", name: "Yellow Dal Tadka", price: 159, diet: "veg" },
      { id: "dal-makhani-signature", name: "Dal Makhani Signature", price: 229, diet: "veg", hero: true },
      { id: "garden-mix-veg", name: "Garden Mix Veg", price: 199, diet: "veg" },
      { id: "kadhai-paneer-signature", name: "Kadhai Paneer Signature", price: 249, diet: "veg", hero: true },
      { id: "paneer-lababdar", name: "Paneer Lababdar", price: 259, diet: "veg" },
      { id: "mushroom-masala", name: "Mushroom Masala", price: 229, diet: "veg" },
    ],
  },
  {
    id: "non-veg-main-course",
    number: "26",
    title: "Non-Veg Main Course",
    navGroup: "fine-dine",
    emotionalLine: "The dishes LOVBITES is known for.",
    mood: "elegant",
    timeContext: "evening",
    items: [
      { id: "homestyle-chicken-curry", name: "Homestyle Chicken Curry", price: 299, diet: "nonveg" },
      { id: "kadhai-chicken", name: "Kadhai Chicken", price: 329, diet: "nonveg" },
      { id: "butter-chicken", name: "Butter Chicken", price: 329, diet: "nonveg", hero: true },
      { id: "chicken-tikka-masala", name: "Chicken Tikka Masala", price: 339, diet: "nonveg" },
      { id: "mutton-curry-slow-cooked", name: "Slow-Cooked Mutton Curry", price: 429, diet: "nonveg", hero: true },
      { id: "egg-curry", name: "Egg Curry", price: 199, diet: "egg" },
    ],
  },
  {
    id: "breads",
    number: "27",
    title: "Breads",
    navGroup: "fine-dine",
    emotionalLine: "Fresh from the tandoor.",
    mood: "elegant",
    timeContext: "evening",
    items: [
      { id: "tandoori-roti", name: "Tandoori Roti", price: 35, diet: "veg" },
      { id: "butter-tandoori-roti", name: "Butter Tandoori Roti", price: 45, diet: "veg" },
      { id: "classic-naan", name: "Classic Naan", price: 55, diet: "veg" },
      { id: "butter-naan", name: "Butter Naan", price: 65, diet: "veg" },
      { id: "garlic-butter-naan", name: "Garlic Butter Naan", price: 85, diet: "veg" },
      { id: "lachha-paratha", name: "Lachha Paratha", price: 79, diet: "veg" },
    ],
  },
  {
    id: "rice-biryani",
    number: "28",
    title: "Rice & Biryani",
    navGroup: "biryani",
    emotionalLine: "Biryani time.",
    mood: "elegant",
    timeContext: "evening",
    items: [
      { id: "steamed-basmati-rice", name: "Steamed Basmati Rice", price: 129, diet: "veg" },
      { id: "jeera-rice", name: "Jeera Rice", price: 149, diet: "veg" },
      { id: "veg-dum-biryani", name: "Veg Dum Biryani", price: 249, diet: "veg" },
      { id: "chicken-dum-biryani", name: "Chicken Dum Biryani", price: 329, diet: "nonveg", hero: true },
      { id: "mutton-dum-biryani", name: "Mutton Dum Biryani", price: 429, diet: "nonveg" },
    ],
  },
  {
    id: "lunch-meal-combos",
    number: "29",
    title: "Lunch & Meal Combos",
    navGroup: "combos",
    emotionalLine: "Sorted, in one order.",
    mood: "elegant",
    timeContext: "afternoon-evening",
    items: [
      { id: "veg-lunch-express", name: "Veg Lunch Express", price: 249, diet: "veg" },
      { id: "chicken-lunch-express", name: "Chicken Lunch Express", price: 329, diet: "nonveg" },
    ],
  },
  {
    id: "thali-combos",
    number: "30",
    title: "Thali & Combos",
    navGroup: "combos",
    emotionalLine: "Everything, on one plate.",
    mood: "elegant",
    timeContext: "afternoon-evening",
    items: [
      { id: "veg-executive-thali", name: "Veg Executive Thali", price: 349, diet: "veg" },
      { id: "chicken-royal-thali", name: "Chicken Royal Thali", price: 449, diet: "nonveg" },
      { id: "dal-makhani-rice-combo", name: "Dal Makhani Rice Combo", price: 279, diet: "veg" },
      { id: "paneer-lababdar-naan-combo", name: "Paneer Lababdar Naan Combo", price: 329, diet: "veg" },
      { id: "butter-chicken-naan-combo", name: "Butter Chicken Naan Combo", price: 399, diet: "nonveg" },
    ],
  },
  {
    id: "salad-papad",
    number: "31",
    title: "Salad & Papad",
    navGroup: "fine-dine",
    emotionalLine: "The simple side of the table.",
    mood: "elegant",
    timeContext: "evening",
    items: [
      { id: "fresh-garden-salad", name: "Fresh Garden Salad", price: 79, diet: "veg" },
      { id: "masala-papad", name: "Masala Papad", price: 79, diet: "veg" },
    ],
  },
  {
    id: "fine-dine-beverages",
    number: "32",
    title: "Fine Dine Beverages",
    navGroup: "fine-dine",
    emotionalLine: "To finish, or just to pause.",
    mood: "elegant",
    timeContext: "evening",
    items: [
      { id: "mineral-water", name: "Pure Mineral Water", price: 40, diet: "veg" },
      { id: "masala-tea", name: "Masala Tea", price: 59, diet: "veg" },
      { id: "fresh-ginger-tea", name: "Fresh Ginger Tea", price: 69, diet: "veg" },
      { id: "classic-green-tea", name: "Classic Green Tea", price: 69, diet: "veg" },
      { id: "house-coffee", name: "House Coffee", price: 99, diet: "veg" },
      { id: "bold-black-coffee", name: "Bold Black Coffee", price: 89, diet: "veg" },
      { id: "chilled-soft-drink", name: "Chilled Soft Drink", price: 60, diet: "veg" },
      { id: "fresh-lime-spark", name: "Fresh Lime Spark", price: 99, diet: "veg" },
    ],
  },

  // ————— CHICKEN BASKET MICRO-BRAND —————

  {
    id: "chicken-basket",
    number: "33",
    title: "Chicken Basket",
    navGroup: "chicken",
    emotionalLine: "Crispy. Grilled. Unapologetic.",
    mood: "bold",
    timeContext: "evening",
    items: [
      { id: "cb-tandoori-chicken-leg", name: "Tandoori Chicken Leg", price: 179, diet: "nonveg" },
      { id: "cb-crispy-fried-chicken-leg", name: "Crispy Fried Chicken Leg", price: 179, diet: "nonveg" },
      { id: "cb-chicken-tikka", name: "Chicken Tikka", price: 199, diet: "nonveg" },
      { id: "cb-chicken-seekh-kebab", name: "Chicken Seekh Kebab", price: 179, diet: "nonveg" },
      { id: "cb-crispy-chicken-wings", name: "Crispy Chicken Wings", price: 199, diet: "nonveg" },
      { id: "cb-chicken-popcorn", name: "Chicken Popcorn", price: 149, diet: "nonveg" },
      { id: "cb-two-chicken-legs", name: "2 Chicken Legs", price: 329, diet: "nonveg", hero: true, description: "Choice of Fried or Tandoori." },
    ],
  },
];

export const ALL_ITEMS = MENU.flatMap((c) =>
  c.items.map((item) => ({ ...item, categoryId: c.id, categoryTitle: c.title, navGroup: c.navGroup }))
);

export const HERO_EDIT = ALL_ITEMS.filter((i) => i.hero || i.datePick);

export const NAV_GROUP_LABELS: Record<string, string> = {
  breakfast: "Breakfast",
  protein: "Protein",
  coffee: "Coffee",
  burgers: "Burgers & Sandwiches",
  pizza: "Pizza",
  pasta: "Pasta",
  "quick-bites": "Quick Bites",
  chicken: "Chicken",
  "fine-dine": "Fine Dine",
  biryani: "Biryani",
  mocktails: "Mocktails",
  dessert: "Dessert",
  combos: "Combos",
};

export const NAV_GROUP_ORDER = [
  "breakfast",
  "protein",
  "coffee",
  "burgers",
  "pizza",
  "pasta",
  "quick-bites",
  "chicken",
  "fine-dine",
  "biryani",
  "mocktails",
  "dessert",
  "combos",
] as const;

/** Curated online-ordering / delivery menu: high-performing categories only (brief §49). */
export const DELIVERY_NAV_GROUPS = [
  "protein",
  "biryani",
  "chicken",
  "pizza",
  "burgers",
  "combos",
  "coffee",
  "dessert",
];

export const DELIVERY_ITEMS = ALL_ITEMS.filter((i) =>
  DELIVERY_NAV_GROUPS.includes(i.navGroup)
);
